title: Arthur Victor # your name (or website title) here
logo: "/images/fotooficial.png?raw=true" # your photo (or logo) here
description: # your text below (remove <br> elements if you don't need line breaks)
   A data science enthusiast with a strong foundation in Python for data analysis and machine learning. In addition, I also have experience working with Power BI and basic SQL. 
   <br><br>
   I am passionate about leveraging data to drive actionable insights and solve real-world problems. With a keen eye for detail and a natural curiosity, I am always seeking to expand my knowledge and skillset in the field of data science. 
  <a href="https://www.linkedin.com/in/arthur-victor-8b8335229/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

