title: Arthur Victor # your name (or website title) here
logo: "/images/fotooficial.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Olá! Me chamo Arthur. Curioso por natureza, apaixonado por dados e ávido por descobrir novas soluções com Data Science.
  <br><br>
 hm..
  <br><br>
  <a href="https://www.linkedin.com/in/arthur-victor-8b8335229/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
